### ISSUE TITLE
Installation failed from apm

### ISSUE THREAD

**Issue by thblt** [ridderholt/atom-relative-linenumbers#11]
Trying to install relative-line-numbers, whether from apm or from the Atom GUI, fails with a 400 Bad Request:

```
$ apm install relative-line-numbers
Installing relative-line-numbers to /Users/thblt/.atom/packages ✗
Unable to download https://www.atom.io/api/packages/relative-line-numbers/versions/0.1.5/tarball: 400 Bad Request Repository inaccessible
```

If this is a GitHub issue, I can report it upstream (I'm assuming at [atom/atom.io](/atom/atom.io))

Thanks a lot for this plugin — I just came to Atom from vim thanks to vim-mode, and I believe relative line numbers are an absolute necessity for efficient vim-like operation.

**Comment by ghost** [comment]
That's because I have removed this package from the Atom package listing. I haven't had the time to upgrade this package to work with the newest API changes and therefore I removed it.
